#!/bin/bash

if (( "$#" < 2 )); then
    echo "usage: git-commit-on-date DATE MESSAGE [GIT-ARGS]" >&2
    echo "" >&2
    echo "DATE shoold look like ‘Tue Sep 26 21:36:36 2023 +0100’" >&2
    exit 1
fi

date="$1"
message="$2"
shift 2

export GIT_COMMITTER_DATE="$date"
exec git commit --message "$message" --date="$date" "${@}"
