#!/bin/bash

set -e

if [[ $EUID != 0 ]]; then
    echo "This must be run as root!" >&2
    exit 1
fi

for xhci in /sys/bus/pci/drivers/?hci_hcd; do

    if ! cd $xhci; then
        echo "Weird error. Failed to change directory to $xhci" >&2
        exit 1
    fi

    echo "Resetting devices from $xhci..."

    for i in ????:??:??.?; do
        echo -n "Resetting $i..."
        echo -n "$i" >unbind
        echo -n "$i" >bind
        echo -e "\rResetting $i... OK"
    done
done
