#!/bin/bash

if [[ "${#@}" < 1 ]]; then
    echo -e "usage:\n$0 DIR\n$0 ARCHIVE-NAME (DIR | FILE)+\n" >&2
    exit 0
fi

target="${1%%/}"
target="${target/%.bz2}"
target="${target/%.tar}.tar.bz2"

if [[ ! (-e "$target") ]]; then
    if [[ "${#@}" -lt 2 ]]; then
        tar cvf - "$1" | bzip2 -zc -9 -- >"$target"
    else
        tar cvf - "${@:2}" | bzip2 -zc -9 -- >"$target"
    fi
else
    echo "error: file \"$target\" already exists"
fi

