#!/bin/bash

if [[ "${#@}" < 1 ]]; then
    echo -e "usage:\n$0 DIR\n$0 ARCHIVE-NAME (DIR | FILE)+\n" >&2
    exit 0
fi

target="${1%%/}"
target="${target/%.gz}"
target="${target/%.tar}.tar.gz"

if [[ ! (-e "$target") ]]; then
    if [[ "${#@}" -lt 2 ]]; then
        tar cvf - "$1" | gzip -9 - --stdout >"$target"
    else
        tar cvf - "${@:2}" | gzip -9 - --stdout >"$target"
    fi
else
    echo "error: file \"$target\" already exists"
fi

