#!/bin/bash

if [[ "${#@}" < 1 ]]; then
    echo -e "usage:\n$0 DIR\n$0 ARCHIVE-NAME (DIR | FILE)+\n" >&2
    exit 0
fi

target="${1%%/}"
target="${target/%.zstd}"
target="${target/%.tar}.tar.zstd"

options="--ultra -22 -T0 --format=zstd --progress"

if [[ ! (-e "$target") ]]; then
    if [[ "${#@}" -lt 2 ]]; then
        tar cvf - "$1" | zstd $options -c >"$target"
    else
        tar cvf - "${@:2}" | zstd $options -c >"$target"
    fi
else
    echo "error: file \"$target\" already exists"
fi

